services:
  miapp:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/home/app
    environment:
      DB_USER: "root"
      DB_PASSWORD: "admin"
      DB_NAME: "store"

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "store"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
